name: yarn install, build, test, coverage

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: yarn install, build, and test
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "@mcansh:registry=https://npm.pkg.github.com" >> .npmrc
          yarn install
          yarn build
          yarn test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload coverage to codecov
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          
      - name: Lighthouse Check
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: 'https://mcansh.blog,https://mcansh.blog/ruby-project,https://mcansh.blog/rails-project,https://mcansh.blog/sinatra-project,https://mcansh.blog/time-to-hex,https://mcansh.blog/similarities-between-life-and-code,https://mcansh.blog/rack-key-concepts,https://mcansh.blog/javascript-classes,https://mcansh.blog/object-lifecycle-cheatsheet,https://mcansh.blog/html5-progress-element,https://mcansh.blog/why-im-learning-software-development'

